### ISSUE TITLE
Trying to run test unikernel on Amazon EC2 gets Assertion `net_configured' failed

### ISSUE THREAD

**Issue by dukedougal** [Solo5/solo5#104]
I'm trying to run the test virtio ping kernel on Amazon EC2 and when it boots it displays this:

Any suggestions as to what I might have done wrong? thanks.

```
            |      ___|
  __|  _ \  |  _ \ __ \
\__ \ (   | | (   |  ) |
____/\___/ _|\___/____/
multiboot: Using memory: 0x100000 - 0x20000000
TSC frequency estimate is 2400089490 Hz
Hello, World
ABORT: virtio/virtio_net.c:329: Assertion `net_configured' failed
Halted
```

Further info, when I try to build the mirageos static website and run that I get a similar message:

```
TSC frequency estimate is 2400088230 Hz
Solo5: new bindings
STUB: getenv() called
STUB: open() called
STUB: getpid() called
STUB: getppid() called
ABORT: virtio/virtio_net.c:329: Assertion `net_configured' failed
Halted

```

**Comment by mato** [comment]
Hi, you're not doing anything wrong -- the assertion is saying that a network device was expected to be present but none was found.

Solo5 targets either the `ukvm` hypervisor or hypervisors which provide `virtio` devices. Amazon EC2 HVM is based on Xen which uses a different device model. To run MirageOS unikernels there you can use the normal `xen` target.
