### ISSUE TITLE
shutdown behaviour on FreeBSD bhyve

### ISSUE THREAD

**Issue by hannesm** [Solo5/solo5#111]
@mato, could you put your `tets-solo5.sh` into the repository and distribute with solo5?

when I start a MirageOS unikernel (e.g. `static_website_tls` from mirage-skeleton), and  `bhyvectl --destroy --vm=mir-https` it at some point, this command does not return immediately and for some time the system is out of order regarding input (the focussed window receives lots of returns, but no user input action does anything).  once the Mirage bhyve vm is dead, input works again (but this can easily take 20 seconds on my system under load (recompiling ports).  the output of the console is:  is there a different way to stop bhyve vms? (is there a way to list all bhyve vms?)

```
2016-10-31 10:01:33 -00:00: INF [https] listening on 4433/TCP
2016-10-31 10:01:33 -00:00: INF [http] listening on 8080/TCP
vm_run error -1, errno 25
```

not sure where the vm_run error originates from.

any ideas?

**Comment by hannesm** [comment]
I think this can be ignored after learning more:
`pgrep -lf bhyve` lists all the bhyve thingies
`pkill -9 <bhyve-pid>` terminates the bhyve vm gracefully
`bhyvectl --destroy --vm=mir-https` for cleanups (should maybe part of `test-solo5.sh` at the beginning?)

using `pkill` (or `kill`) does not lead to the behaviour described above.

(leaving this issue open to remind mato to put the shell script into this repo :)

**Comment by mato** [comment]
@hannesm I regularly use `killall bhyve` when testing and that has immediate effect. I suspect the behaviour you're seeing might be due to your running bhyve with ACPI enabled (`-A`) and it's trying to send an ACPI soft-off to the guest to terminate it "politely".

Regarding the "run" script, that's on my list for this week.

**Comment by mato** [comment]
See #112 for a work in progress run script.

**Comment by hannesm** [comment]
thx!
