### ISSUE TITLE
virtio: bhyve limits vmname to 8 characters

### ISSUE THREAD

**Issue by hannesm** [Solo5/solo5#141]
"mir-nqsbio" doesn't work with bhyve flawlessly (affects `tools/run/solo5-run-virtio.sh`)

we should crop the vmname if the given thing is too large.

we may want to remove "mir-" prefix from all mirage generated binaries (to be fixed separately in mirage tool)...

**Comment by mato** [comment]
An 8 character limit is a bit daft. Perhaps we could just use `vm<PID>` for the purposes of `solo5-run-virtio`?

**Comment by hannesm** [comment]
mirage now does not add a `mir-` prefix anymore, see https://github.com/mirage/mirage/pull/725

maybe the PID approach is good for `solo5-run-virtio` if the kernel name (without `.virtio`) is longer than 8 characters.  another option would be to sub the first 8 characters and hope there is no collision.

**Comment by mato** [comment]
Fixed in #145.
