### ISSUE TITLE
gdb breakpointing is relying on single stepping every instruction

### ISSUE THREAD

**Issue by ricarkol** [Solo5/solo5#16]
Right now, in order to break on a specific function we are single stepping on every single instruction running in the VM and comparing the current PC to a list of breakpoints. This is extremely slow because the vcpu is exiting for every single instruction (although it works). Ideally, we could use some other technique:
1. mark the page as invalid so we only get exits on the page that includes the breakpoint (the instruction).
2. update the guest memory with some breakpoint instruction, so we get an exit just for the breaking instruction.
3. use some KVM API for this. There has to be some KVM api to break on a specific PC. Can't find it in the docs and QEMU does not seem to be using any. But there has to be something...

**Comment by mato** [comment]
Fixed in #198.
