### ISSUE TITLE
native FreeBSD vmm port

### ISSUE THREAD

**Issue by dstolfa** [Solo5/solo5#167]
The current support for bhyve is via VirtIO, have there been any plans to support bhyve natively, and would something like a [hypercall ABI](https://reviews.freebsd.org/D8100) be of any help in terms of functionality or performance with addition of various hypercalls?

**Comment by djwillia** [comment]
I'm not aware of plans to support bhyve natively.  

More likely would be to support the "ukvm" backend for FreeBSD.  ukvm is a "unikernel monitor" which sits in the same place in the system diagram as bhyve would.  Currently, ukvm only runs on Linux and uses the kernel KVM API to set up the context for unikernels.  I have a branch in my tree that ports ukvm to MacOSX, using the kernel Hypervisor.framework API to set up the unikernel context.  We are trying to figure out the cleanest way to have both of these different kernel APIs coexist.  The hope would be that we can then also add the FreeBSD kernel API as a third.

**Comment by dstolfa** [comment]
So if I understood correctly with your comment and looking at the code in your repo, the idea would be to do it through something like vmmapi.h in FreeBSD and interface with bhyve that way?

**Comment by djwillia** [comment]
Yeah that's right... I'm probably confused about what the term byhve refers to.  Is it the name of both the user and kernel portions?  I was thinking that the unikernel monitor (the ukvm equivalent in userspace) would interface through something like vmmapi.h to the FreeBSD kernel support for virtualization.  The user-space bhyve code would not be needed to run unikernels in that mode.

**Comment by mato** [comment]
That's correct. I'm currently working on (yet another iteration of) a refactoring of Solo5/ukvm, which will allow for easy porting of ukvm to the FreeBSD vmmapi. In fact, I may end up doing a port as part of validating my abstractions since unlike @djwillia I don't use aMac.

**Comment by mato** [comment]
@djwillia Yeah, the term "bhyve" refers to the whole FreeBSD hypervisor project and also the userspace bhyve process, it's confusing. Somewhat like Solo5 referring to both the project and the unikernel base layer :-) Anyway, vmmapi.h & friends is the "thing" we'd be porting to.

**Comment by mato** [comment]
The FreeBSD vmm port has been merged as part of #171 so I'm closing this.
