### ISSUE TITLE
Refactor/rewrite ukvm gdb module

### ISSUE THREAD

**Issue by mato** [Solo5/solo5#176]
The GDB module code is hacked together from various sources and is generally in a dire state. It should be refactored (probably implies a rewrite) into two separate parts:

1. The GDB server and protocol code, ideally arch- and backend- independent and engineered from an actual protocol description (or reading the GDB source code, no idea how much documentation exists for the protocol).
2. Initially an x86_64 (KVM ...) backend implementation since that's what is there today.

Ideally as part of the refactoring the 1st part would be arch- and backend- independent (as in the changes in #171), then the 2nd part could gain features like using hardware breakpoints rather than single-stepping, plus fix various other outstanding issues (#16, #25).

Help wanted. Any takers? This is an extremely useful and fairly self-contained project.

**Comment by ricarkol** [comment]
Will start working on this. Does anybody want to collaborate?
