### ISSUE TITLE
[Question] Port to OpenBSD - Linking Problem (recompile with -fPIC)

### ISSUE THREAD

**Issue by adamsteen** [Solo5/solo5#203]
Hi

I am attempting to port Solo5 to OpenBSD (Virtio only), I think i have the kernel and test_hello compiling but when it comes to linking test_hello i get the following error.

/home/asteen/devl/solo5/kernel/virtio/solo5.o: relocation R_X86_64_32 against 'a local symbol' can not be used when making a shared object; recompile with -fPIC [1]

adding -fPIC to HOST_CFLAGS doesn't seem to help (HOST_CFLAGS="-fPIC -nostdlibinc") 

My changes to the configure script are located [here](https://github.com/Solo5/solo5/compare/master...adamsteen:master)

Could anyone point me right direction to get this working? The full build log is attached. [Full Build Log](https://github.com/Solo5/solo5/files/1080496/build.txt)

Cheers
Adam

PS I am new to c and make files, but i had to pick somewhere to start, and solo5 has piqued my interest.

[1]
`clang -fPIC -nostdlibinc -ffreestanding -mno-red-zone -isystem /home/asteen/devl/solo5/include-host -std=gnu99 -Wall -Wextra -Werror -O2 -g -I/home/asteen/devl/solo5/kernel -c test_hello.c -o test_hello.o
ld -T /home/asteen/devl/solo5/kernel/virtio/solo5.lds \
		 -nostdlib -z max-page-size=0x1000 -static -o test_hello.virtio /home/asteen/devl/solo5/kernel/virtio/solo5.o test_hello.o 
ld: /home/asteen/devl/solo5/kernel/virtio/solo5.o: relocation R_X86_64_32 against 'a local symbol' can not be used when making a shared object; recompile with -fPIC
/home/asteen/devl/solo5/kernel/virtio/solo5.o: could not read symbols: Bad value
gmake[2]: *** [../Makefile.tests:64: test_hello.virtio] Error 1
gmake[2]: Leaving directory '/home/asteen/devl/solo5/tests/test_hello'
gmake[1]: *** [GNUmakefile:43: _test_virtio_hello] Error 2
gmake[1]: Leaving directory '/home/asteen/devl/solo5/tests'
gmake: *** [GNUmakefile:33: virtio] Error 2
`

**Comment by mato** [comment]
Hi,

> /home/asteen/devl/solo5/kernel/virtio/solo5.o: relocation R_X86_64_32 against 'a local symbol' can not be used when making a shared object; recompile with -fPIC [1]
> 
> adding -fPIC to HOST_CFLAGS doesn't seem to help (HOST_CFLAGS="-fPIC -nostdlibinc") 

-fPIC should not be involved at this stage. Does OpenBSD configure clang to
build PIE exectuables by default? If that's the case then adding -no-pie
might help (but will run into trouble later due to mixing of PIC/non-PIC
code in Mirage build systems).

> 
> My changes to the configure script are located [here](https://github.com/Solo5/solo5/compare/master...adamsteen:master)

Those look fine.

> /home/asteen/devl/solo5/kernel/virtio/solo5.o: could not read symbols: Bad value

Can you post the output of "nm" for this object file?

**Comment by adamsteen** [comment]
@mato 
Thanks for the input

I tried a few combinations of pic/no-pic and pie/no-pie and nothing changed, so removed it before running nm. I don't know if openbsd configures clang to build PIE executables by default, but it looks like i will have to dig further.

Please see the attached [nm.lo](https://github.com/Solo5/solo5/files/1082183/nm.txt)

**Comment by adamsteen** [comment]
I made a post on OpenBSD-Misc and got the following reply, it doesn't mean much to me, but might to others

On Fri, 16 Jun 2017, Adam Steen wrote:
> I am attempting to port Solo5 to OpenBSD (Virtio only), I think i have
> the kernel and test_hello compiling but when it comes to linking
> test_hello i get the following error.
>
> /home/asteen/devl/solo5/kernel/virtio/solo5.o: relocation R_X86_64_32
> against 'a local symbol' can not be used when making a shared object;
> recompile with -fPIC [1]
...
> clang -fPIC -nostdlibinc -ffreestanding -mno-red-zone -isystem
> /home/asteen/devl/solo5/include-host -std=gnu99 -Wall -Wextra -Werror
> -O2 -g -I/home/asteen/devl/solo5/kernel -c test_hello.c -o
> test_hello.o

That part is okay.


> ld -T /home/asteen/devl/solo5/kernel/virtio/solo5.lds \
> -nostdlib -z max-page-size=0x1000 -static -o test_hello.virtio
> /home/asteen/devl/solo5/kernel/virtio/solo5.o test_hello.o

This part is not.  Projects aiming for portability should build both
executable and shared libraries via the compiler driver ('clang', 'cc', or
'gcc') and *not* by invoking ld directly.

This is because the objects generated by the C compiler may depend on the
presence of symbols provided by objects or options supplied by the
compiler driver.  That's true not just on OpenBSD but on Linux as well.


In this case, you've almost certainly hit the need for the __guard_local
symbol, which is provided by crtbeginS.o

(Note: crtbeginS.o itself needs another object supplied by the compiler
driver, so don't even _think_ of pulling it in manually!)

**Comment by adamsteen** [comment]
Good Morning Mato

Feel free to close this for now, i am setting up a FreeBSD box to act as a comparison point.

After further investigation but no further success, i think i am linking in system object files which have been compiled with PIC. I will keep digging and hopefully produce a PR.

**Comment by mato** [comment]
@adamsteen:

> After further investigation but no further success, i think i am linking in system object files which have been compiled with PIC. I will keep digging and hopefully produce a PR.

Yes, that's probably what's happening.

> This part is not. Projects aiming for portability should build both executable and shared libraries via the compiler driver ('clang', 'cc', or 'gcc') and not by invoking ld directly.

In our case we're linking what the OpenBSD developers would consider a "kernel", so this doesn't apply.

I'll close this for now, feel free to submit a PR once you have something working.
