### ISSUE TITLE
make devices asynchronous

### ISSUE THREAD

**Issue by djwillia** [Solo5/solo5#21]
The device interfaces in the Solo5/Mirage bindings are synchronous, while the rest of Mirage is asynchronous.  The Solo5 bindings need to support asynchronous operation.  

To do this properly for Mirage, it looks like some of the abstractions in the Xen platform (or similar) need to be supported (e.g., evtchn, time, activations).  Some things that seem to be in the right direction:

https://github.com/djwillia/mirage-platform/blob/master/xen/lib/main.ml#L60
https://github.com/djwillia/mirage-platform/blob/master/xen/lib/time.ml
https://github.com/djwillia/mirage-platform/blob/master/xen/lib/activations.ml

**Comment by mato** [comment]
Current plan is not to do asynchronous bindings, so closing this.
