### ISSUE TITLE
Missing include in ukvm_hv_kvm_x86_64.c and friends

### ISSUE THREAD

**Issue by fwsGonzo** [Solo5/solo5#221]
Should include `malloc.h`

See https://github.com/hioa-cs/IncludeOS/issues/1540

**Comment by ricarkol** [comment]
Thanks for the report @fwsGonzo . This should be fixed on the latest master (IncludeOS is not pointing to the latest). I'm double checking that our master builds correctly in ubuntu:17.10 (and that the `malloc.h` include is there); if all good, then will create a PR in IncludeOS to point to the latest solo5.
