### ISSUE TITLE
Questions on building and setting up solo5

### ISSUE THREAD

**Issue by niks3089** [Solo5/solo5#225]
Hi,

I am trying to build solo5 but I am confused and did not understand the "building" part in the read me file

This is what is mentioned in document

> Support for Solo5 as a target is integrated since the release of MirageOS 3.0, which adds two new targets to the mirage configure command:

However, I am unable to find such targets
```
nikhil@nikhil-desktop:~$ mirage --version
3.0.5
nikhil@nikhil-desktop:~$ mirage configure -t virtio
mirage: unknown option `-t'.
Usage: mirage configure [OPTION]... 

```
mirage configure --help also doesn't mention the targets supported.

```
CONFIGURE OPTIONS
       -b DIR, --build-dir=DIR
           The directory where the build is done.

       -f FILE, --file=FILE (absent=config.ml)
           The configuration file to use.

```

> You can build for either of these targets using the standard MirageOS build process, which will output either a .ukvm or .virtio unikernel binary.

Can you please expand what needs to be  done specifically for solo5?  MirageOS installation process doesn't mention anything about solo5 so I think it's better if it can be mentioned here

I tried installing like follows
```
opam install mirage-solo5
opam install solo5-kernel-virtio

```
How do we actually build solo5? What are the steps that needs to be followed?

> 
A specialized monitor called ukvm-bin is generated as part of the build process, so the command line arguments may differ depending on the needs of the unikernel. To see the arguments, run ukvm-bin with no arguments or --help.

How do we build ukvm-bin? 

How do we build solo5 from source? Let's say I want to change something in solo5 and test if it works, how to test it and what needs to be done? 

Is 
```
./confiure.sh
./build.sh
```
sufficient?

**Comment by ricarkol** [comment]
Hi @niks3089 . First of all, sorry for the README, we are in the process of improving it.

Solo5 is really designed to be used by a unikernel libos like MirageOS or IncludeOS. But, you can build it alone without a libos on top of it, and run tests like this:

```
[solo5]$ make
[solo5]$ cd tests/
[tests]$ bash setup-tests.sh # will create a tap device
[tests]$ bash run-tests.sh  # will run all tests
[tests]$ ./test_hello/ukvm-bin ./test_hello/test_hello.ukvm # run hello world using ukvm
```
If you want to use solo5 from MirageOS, follow the instructions here: https://github.com/mirage/mirage-skeleton
If you want to use solo5 from IncludeOS, follow the instructions at https://github.com/hioa-cs/IncludeOS, and then run `test_ukvm.sh` to try an example web server running on solo5/ukvm.

**Comment by niks3089** [comment]
Hi @ricarkol,

Thanks. Is it possible to run packages such as redis by modifying it's build and having it run on solo5?

**Comment by ricarkol** [comment]
In theory yes, but you would like to implement a network stack. That's why we get the network stack from Mirage or IncludeOS. The best way would be to run redis on top of IncludeOS as it has a POSIX'ish layer. Don't know if that POSIX layer is enough for redis, but it's worth a try. Try asking on teh IncludeOS gitter chat channel at https://gitter.im/hioa-cs/IncludeOS.

**Comment by niks3089** [comment]
Thanks @ricarkol, Another question about debugging, if there is an application crash,  will a core file be generated? Is it possible to access it?

**Comment by ricarkol** [comment]
Hey @niks3089 , sorry, we don't generate a core file. Linux will generate one if `ukvm-bin` crashes, which would include the unikernel memory, but at the moment there is no tooling to do anything with that.

**Comment by niks3089** [comment]
I would like to build a debugging tool for solo5 to help debug application crashes. Any comments or gotchas I need to be aware of?

**Comment by niks3089** [comment]
I would like to build a debugging tool for solo5 to help debug application crashes. Any comments or gotchas I need to be aware of?

**Comment by ricarkol** [comment]
Just some comments and ideas. First of all, you could use https://github.com/Solo5/solo5/blob/master/tests/test_exception/test_exception.c#L34 as the "test". Most crashes (i.e., like a page fault) ends up calling PANIC() (https://github.com/Solo5/solo5/blob/8dc4934f4ce6f28f1dec0f297281e7100d71031f/kernel/cpu_x86_64.c#L171).  PANIC then eventually calls `platform_exit()`. The issue there is that every unikernel (succeeding or crashing) ends up calling `platform_exit()`. You should start by making it return a `rc` or something that lets the monitor know that something went wrong. Then, at the monitor level (let's focus on ukvm), you have to handle that `platform_exit` and dump the core. That would happen here: https://github.com/Solo5/solo5/blob/f3dd5031ef8ec3ba64b9fd2d8fc454d08247d382/ukvm/ukvm-core.c#L473. You might have to add a hypercall for `platform_exit` or `platform_abort` or something like that. A core undestandable by GDB (let's just focus on GDB) looks like an ELF apparently (http://www.gabriel.urdhr.fr/2015/05/29/core-file/). Don't know much about that part, but I guess you would have to copy the executable (i.e., `test_exception.ukvm`) and add memory (and registers) into it.

**Comment by niks3089** [comment]
Thanks @ricarkol , Going to start looking at it right away!

**Comment by niks3089** [comment]
If I have any questions, Is there a channel where I can post questions and get quick response? Looked for it but didn't find it. Thanks

**Comment by ricarkol** [comment]
@mato , do you know what's the procedure to add somebody to the ocamlabs slack channel?

**Comment by yomimono** [comment]
I'm not @mato, but the procedure is to ask @GemmaG to add them.  I think an e-mail address is needed.

**Comment by ricarkol** [comment]
Thanks @yomimono 

@niks3089 what's your email?

**Comment by niks3089** [comment]
My email is niks3089@gmail.com

**Comment by niks3089** [comment]
Also, how do I put the test_exception piece of code under gdb?  I added gdb to UKVM_MODULES in Gnumakefile in test_exception directory and tried to run "./ukvm-bin test_exception.ukvm --gdb" but ran to completion

**Comment by ricarkol** [comment]
It's the other way around:

```
[test_exception]$ ./ukvm-bin --gdb test_exception.ukvm 
ukvm-bin: Waiting for a debugger. Connect to it like this:
ukvm-bin: 	gdb --ex="target remote localhost:1234" KERNEL
```

and from another console:

```
[test_exception]$ gdb --ex="target remote localhost:1234" test_exception.ukvm
GNU gdb (GDB) Red Hat Enterprise Linux 7.6.1-100.el7
Copyright (C) 2013 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-redhat-linux-gnu".
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>...
Reading symbols from /home/kollerr/research/solo5/tests/test_exception/test_exception.ukvm...done.
Remote debugging using localhost:1234
_start (arg=0x5000) at ukvm/kernel.c:24
24	{
(gdb) s
28	    console_init();
(gdb) 
console_init () at ukvm/console.c:39
39	{
(gdb) 
_start (arg=0x5000) at ukvm/kernel.c:29
29	    cpu_init();
(gdb) 
cpu_init () at cpu_x86_64.c:153
153	{
```

**Comment by mato** [comment]
Folks, this is an issue tracker, not a discussion forum. For discussion please use the MirageOS mailing list at https://lists.xenproject.org/cgi-bin/mailman/listinfo/mirageos-devel or `#mirage` on IRC (Freenode). Thanks.
