### ISSUE TITLE
Solo5 on ARMv7 (little-endian)

### ISSUE THREAD

**Issue by dinosaure** [Solo5/solo5#243]
Hi,

I just acquired a server with an ARMv7 (little-endian) processor. Then, I would like to compile Solo5 on this server but the `configure.sh` die when it recognize this architecture.

I saw some issue about ARM and merged PR about that, I would like to know the status of Solo5 on ARM.

Thanks.

**Comment by mato** [comment]
On Saturday, 17.02.2018 at 14:51, Calascibetta Romain wrote:
> Hi,
> 
> I just acquired a server with an ARMv7 (little-endian) processor. Then, I would like to compile Solo5 on this server but the `configure.sh` die when it recognize this architecture.

Please provide:

  - More details about your server: Machine type, Linux distribution,
    output of "cat /proc/cpuinfo".
  - The full output of "configure.sh".
  - The output of "cc -dumpmachine".

> I saw some issue about ARM and merged PR about that, I would like to know the status of Solo5 on ARM.

Solo5 only supports AARCH64 (ARM64) hardware, not 32-bit ARM. Other than
that, the ARM support is fairly experimental and has not had much
real-world testing.

-mato

**Comment by mato** [comment]
I thought so, but wanted to double-check as you mentioned "ARM server". In that case, there's nothing we can do, 32-bit ARM is unlikely to be supported in the near future, if ever, as Solo5 depends on hardware virtualization that is not present on that architecture.
