### ISSUE TITLE
Multiple NICs case not possible

### ISSUE THREAD

**Issue by justinc1** [Solo5/solo5#248]
Per readme, I can have only one NIC:
The following devices are supported by the Solo5 virtio target:
    a single virtio network device attached to the PCI bus

Is there intention to support multiple NICs? Firewall  is an obvious usecase.

**Comment by mato** [comment]
This is on the roadmap and likely to be done within the next few months, however not in the next formal release (#217).

**Comment by jbarraca** [comment]
are there any updates on multiple NICs ?

**Comment by mato** [comment]
Not at the moment.
