### ISSUE TITLE
Better arg handling for ukvm

### ISSUE THREAD

**Issue by djwillia** [Solo5/solo5#26]
`ukvm` cmdline argument handling needs to be fixed.  From @avsm on slack:

> also support the gnu convention of `--` after `<binary>`? Otherwise `-gdb` is ambiguous

Also, the network and disk information will need to be optional when those parts of ukvm are optional modules.

**Comment by mato** [comment]
@djwillia In #41 I had to change the command line for ukvm to be `<disk> <tap> <elf> [--gdb] [args]`, i.e. move `--gdb` to come before the unikernel arguments. I've deliberately not done more than that now as I don't want to step on the work you're doing on the `modularize` branch which affects ukvm command line parsing.

**Comment by mato** [comment]
Fixed ages ago (mostly by #57)
