### ISSUE TITLE
Using stdlib functions

### ISSUE THREAD

**Issue by qkeksz** [Solo5/solo5#265]
Hey there!

Relatively new to the whole FaaS scene and I seem to have a problem ot I might just be dumb. For a test I'm trying to use the C system() function and I always get the undefined reference error. I have added stdlib.h and a lot of other files to the include-host directory, but it doesn't seem to help. I also tried using #include with both <>-s and ""-s (yes, the path was correct).

Any help would be appreciated, thanks.

**Comment by mato** [comment]
That won't work. Solo5 only provides the interfaces defined in `kernel/solo5.h`.

If you want to use more of the C stdlib, you'll have to port it from somewhere (e.g. musl) as an additional layer yourself. See also e.g. the https://github.com/mirage/ocaml-freestanding layer which does this for the OCaml runtime for MirageOS running on top of Solo5.

Closing this, as this is not the right forum for questions. Please follow up on the mailing list if interested.
