### ISSUE TITLE
Quotes in hvt boot parameters get lost

### ISSUE THREAD

**Issue by ansiwen** [Solo5/solo5#281]
If the unikernel boot parameter values contain double quotes (") they correctly end up in the Key_gen module if it is compiled for the unix target. In the hvt case the quotes get lost and must be escaped with an addition backspace (\\"). In any case I believe it should be consistent and behave in the same way for unix and hvt targets.

**Comment by mato** [comment]
This is the same underlying code as that referred to in mirage/mirage-solo5#33, let's discuss there.
