### ISSUE TITLE
Enable Stack Protector

### ISSUE THREAD

**Issue by mato** [Solo5/solo5#293]
Currently, we explicitly disable any stack protector that the host toolchain may be using. This is undesirable, instead we would like to compile all C code (bindings and "user") with `-fstack-protector-strong`.

Requires implementing `__stack_chk_fail()`, initialising `__stack_chk_guard` suitably in bindings `_start()` and appropriately adjusting the build system's flags.

References: Original GCC SSP paper at ftp://gcc.gnu.org/pub/gcc/summit/2003/Stackguard.pdf, this [post](https://www.elttam.com.au/blog/playing-with-canaries/) provides a good break-down of current implementations canary setup.

**Comment by mato** [comment]
Work in progress in #294; depends on #296 for various obscure ABI reasons.

**Comment by mato** [comment]
I was a bit over-zealous in closing this, as #294 has fixes for Linux and FreeBSD but not for OpenBSD.

@adamsteen:

> yeah test_ssp [on OpenBSD] fails with an abort. [ABORT: Fatal trap]

The test is aborting with a fault due to corrupting it's stack, but with SSP this would be detected earlier and the test would abort with "Stack corruption detected" instead. I'll fix `tests.bats` to check for the latter correctly.

> a note on OpenBSD and test_ssp, OpenBSD switched to using lld (LLVM/Clang 6.0.0) as of 2018-10-22 so its in the same boat as FreeBSD with regard to -mstack-protector-guard=global

Yes, but the actual implementation of what -fstack-protector-X does on an LLVM/Clang configured for OpenBSD appears to differ. From the LLVM source code, in TargetLoweringBase::getIRStackGuard():

https://github.com/llvm-mirror/llvm/blob/master/lib/CodeGen/TargetLoweringBase.cpp#L1633-L1642

From my limited understanding of that code I can't tell what ABI the compiler is expecting on OpenBSD. The few mentions I can find on the OpenBSD site regarding "ProPolice" don't describe the ABI and mostly talk about ProPolice introduction way back in OpenBSD 3.x which still used GCC. Can you try and find out what the expected ABI is?

**Comment by adamsteen** [comment]
Hi @mato 

I just complete a quick prototype for this issue, and I think it works, but i am not sure how to integrate this into the main repo

please see [SSP for OpenBSD](https://github.com/adamsteen/solo5/pull/7)

**Comment by mato** [comment]
@adamsteen Now that #351 has been merged, I guess we can close this? Or is there anything else remaining for SSP on OpenBSD toolchains?

**Comment by adamsteen** [comment]
Yes, we can close this!

Nothing left that I know of!
