### ISSUE TITLE
Unmap zero page; forcibly disable TLS

### ISSUE THREAD

**Issue by mato** [Solo5/solo5#296]
We are currently running on both hvt and virtio with the page at VA 0x0 mapped. As a standard hardening and debugging measure, we should leave this page unmapped (not present) in the guest so that the following is enforced:

1. `NULL` pointer dereference results in `#PF`.
2. On x86_64, TLS access via `%fs` or `%gs` currently silently returns garbage (well, `0x0` on hvt) as the default values of `IA32_FS_BASE` and `IA32_GS_BASE` are zero. Until such time that we get around to supporting TLS these accesses should likewise result in `#PF`.

**Comment by ricarkol** [comment]
This is pretty bad. I was sure we had the first page unmapped, but nope, it's there:

https://github.com/Solo5/solo5/blob/68d374a8948b420d61208c7ec7034667eb8e1b88/tenders/hvt/hvt_cpu_x86_64.c#L67-L68

**Comment by mato** [comment]
@ricarkol I've known about this for ages, but only now with working on SSP/ASLR/... am getting around to hardening these things properly. See #297 for a WIP fix.

**Comment by mato** [comment]
@Weichen81 Would you have time/are you available to implement the ARM64 equivalent of the changes made in #297 to the tender's page table setup to unmap the zero page and map the rest of (VA < 1M) as on x86_64?

I have at least written the relevant test cases, which are currently "expected to fail", but my understanding of the ARM64 paging scheme is not quite up to making the rest work. Let me know even if you can't work on this and I'll either find someone who can or figure it out myself.

**Comment by Weichen81** [comment]
@mato it’s ok, I can do it. And I will start to do it on Friday or next week, after I finish the work at hand. How do you think about it?

**Comment by mato** [comment]
@Weichen81 Yes, thanks! No hurry, I probably won't merge #297 before Monday anyway (need to wait for @Kensan to check out the Muen implications). In any case, the ARM64 changes can be done in a separate follow-up PR, so even if #297 is not merged when you start please base your work on top of it. 

Also, if you could at some point review the parts I did do in #297 (test cases, TPIDR_EL0 init) just to make sure I haven't gotten something subtly wrong that would be a great help.

**Comment by Weichen81** [comment]
@mato OK, I will go to have a look #297

**Comment by Weichen81** [comment]
@mato I have looked the code, because current code only support 2MB mapping. In order to unmap  zero page, I should add a PTE  table for first 2MB block to manage the memory in 4KB. I would send a PR to fix it today or tomorrow.

**Comment by mato** [comment]
@Weichen81 Yes, that's similar to what I had to do for `x86_64`. Don't forget that you can check with both `test_zeropage` and `test_ssp` which are part of #297 / #294 , both of those should pass, i.e. abort with an exception once the zero page has been unmapped. Run them manually, not through `tests/run-tests.sh` as I have them marked "expected to fail" there to get CI to pass.
