### ISSUE TITLE
Question: is possible to build a nginx unikernel?

### ISSUE THREAD

**Issue by devimc** [Solo5/solo5#314]
in other unikernels like rumprun it's possible https://github.com/rumpkernel/rumprun-packages/tree/master/nginx

**Comment by ricarkol** [comment]
Hi @devimc. Solo5 is not a unikernel. It is a base for unikernels like mirage, rumprun, and includeos. If you want to run rumprun+nginx on top of solo5, take a look at this: https://github.com/nabla-containers

**Comment by devimc** [comment]
@ricarkol thank you so much!
closing issue
