### ISSUE TITLE
Memory layout printout is not right

### ISSUE THREAD

**Issue by ricarkol** [Solo5/solo5#317]
This is what I get on Linux x86_64 on svt, hvt, and virtio (any of the test unikernels). Tried gcc 5 and 7 on an Ubuntu xenial.

```
            |      ___|
  __|  _ \  |  _ \ __ \
\__ \ (   | | (   |  ) |
____/\___/ _|\___/____/
Solo5: Memory map: %lu MB addressable:
Solo5:   reserved @ (0x0 - 0x%lx)
Solo5:       text @ (0x%lx - 0x%lx)
Solo5:     rodata @ (0x%lx - 0x%lx)
Solo5:       data @ (0x%lx - 0x%lx)
Solo5:       heap >= 0x%lx < stack < 0x%lx
```
After reading a bit of `bindings/ee_printf.c`, it seems that our printf library doesn't support the `%ll` modifier (so no `%llu` nor `%llx`). @adamsteen: is this happening on openbsd as well?

**Comment by mato** [comment]
Uh, yeah. Looks like #309 wasn't actually tested.

ee_printf is pretty bad anyway, so I replace it in #318 with a better printf.

**Comment by adamsteen** [comment]
@mato @ricarkol

Sorry about this, I get the same problem.  #318 fixes this for OpenBSD as well.
