### ISSUE TITLE
virtio IRQ is fixed to IRQ11, should be dynamic

### ISSUE THREAD

**Issue by mato** [Solo5/solo5#32]
While debugging my changes for a blocking solo5_poll() I ran into the following with `mir-stackv4`:

For some reason, QEMU on my system has decided to assign IRQ10 instead of IRQ11 to the virtio-net device. This results in tons of messages `got irq 10 at 0xXXXXXXXX` from `low_level_handle_irq()`. Changing the hard-coded IRQ number in `low_level_handle_irq()` to 10 (0xA) confirms that this is the problem.

The virtio code needs to be fixed to dynamically determine which IRQ the device is using.

FYI, the QEMU runes I'm using which trigger this behaviour:

````
qemu-system-x86_64 -vga none -nographic -kernel ../../solo5/loader/loader -initrd mir-stackv4.virtio -device virtio-net,netdev=n0 -netdev tap,id=n0,ifname=tap100,script=no,downscript=no -drive file=/dev/zero,if=virtio
````

**Comment by ricarkol** [comment]
The interrupt number is obtained here on init: https://github.com/djwillia/solo5/blob/master/kernel/virtio/pci.c#L71. I'll work on a fix.

**Comment by mato** [comment]
@ricarkol I've pushed a *temporary* hack to "fix" this in #35, just so that I don't have to keep carrying the patch in my tree. The change also adds a diagnostic print to `virtio_config()`. The output on my QEMU invocation shows that separate IRQs can be assigned to either virtio device:

````
$ qemu-system-x86_64 -enable-kvm -vga none -nographic -kernel loader/loader -initrd kernel/test_ping_serve.virtio  -device virtio-net,netdev=n0 -netdev tap,id=n0,ifname=tap100,script=no,downscript=no -drive file=/dev/zero,if=virtio
            |      ___|  
  __|  _ \  |  _ \ __ \  
\__ \ (   | | (   |  ) | 
____/\___/ _|\___/____/  
Initializing the KVM Paravirtualized clock.
virtio_config: device_id=1, interrupt_line=a
Found virtio network device with MAC: 52 54 00 12 34 56 
virtio_config: device_id=2, interrupt_line=b
host features: 71000ed4: 2 4 6 7 9 10 11 24 28 29 30 
Found virtio block device with capacity: 0 * 512 = 0
````
A proper fix would be to introduce some infrastructure (but think about whether it is common or target-specific) to install IRQ handlers internally, e.g. interrupt_register(handler) / interrupt_unregister(handler). For simplicity I think a single handler-per-interrupt is fine, so the common code could just use a static array of pointers to handlers.

**Comment by mato** [comment]
Updating with discussion from Slack: Consensus is that we can leave my temporary fix in for now. Leaving this issue open as a full fix will be needed once we implement a "device"/"events" abstraction for Solo5.

**Comment by mato** [comment]
FreeBSD/bhyve is also affected by this as it uses irq 5.
