### ISSUE TITLE
Remove specialization of hvt tender at unikernel compile time

### ISSUE THREAD

**Issue by mato** [Solo5/solo5#326]
A long-standing design [issue](https://www.mail-archive.com/solo5@lists.h3q.com/msg00024.html) in Solo5 is the specialization of the hvt tender being done at unikernel compile time, which is a hold-over from the days of ukvm.

With the introduction of the spt tender the problem has become even more pronounced, so the time has come to remove this concept from the codebase.

Among other things (see linked mailing list post for more), this change is blocking:

- A sane supply chain, allowing the _operator_ (not the _developer_) to supply the solo5-hvt tender. This is a pre-requisite for a better deployment story, e.g. integration with libvirt-based systems for deployment.
- Sharing code between the hvt and spt tenders (e.g. ELF loader, common host device/module setup code).
- Support for multiple instances of block/network devices, and support for "future" devices (e.g. host-only communication channels).

The following sub-tasks are part of this work:

1. [x] Build system re-factoring (see comment below) and removing hvt compile-time specialization with minimal changes to the current codebase. (#345)
2. [x] Share common code between tenders. (#364)
Details:

1. As a start, we will build ~~one `solo5-hvt`~~ two tenders, `solo5-hvt` with all non-debug modules and `solo5-hvt-debug` including debug modules. the tender will allow any combination of devices to be enabled at run time, i.e. post this step it will no longer _enforce any contract_ between the unikernel and its host on what resources (network, block devices) are required by the unikernel to run.
2. Tenders need to be able to share common code, as the upcoming support for multiple devices will introduce more common functionality.

After this is complete I will raise a separate issue to deal with the actual implementation of multiple device support and adding back the _enforcement_ of the host/unikernel contract by the tender as the two are ultimately intertwined.

**Comment by mato** [comment]
Progress update: Working on this has led to an overdue refactoring of the build system, with the following overall goals:

1. Correct dependency handing. i.e. `make` must always rebuild what has changed, with a minimal amount of dependencies specified manually in Makefiles.
2. Clear data flow throughout the build system. The build system needs to produce four groups of artifacts (bindings for _A_ targets, _B_ tenders for the host, _C_ tests for _A_ targets and _D_ .pc files for use by OPAM), using different compilers (or flags). As things currently stand, the number of combinations leads to unmaintainable spaghetti code.
3. Removing as much repetition as possible, without going too deep into GNU make "magic" (limiting use of macros and `$$$$(FOO)` unless absolutely necessary). Otherwise use best practices where possible.
4. Allow for sharing of common code between tenders.

Unfortunately there are _far_ too many ways to shoot oneself in the foot with GNU make, so this will take some time to stabilise.

For those that want to follow along, my work in progress branch is at https://github.com/mato/solo5/tree/wip-no-specialization. This is not yet functional with OPAM/MirageOS.

**Comment by mato** [comment]
Progress update: The last week or so has been spent writing an end to end smoketest for Mirage/Solo5, and learning a lot of OCaml along the way! The E2E test is needed in order for me to be able to reproducibly test Solo5 API and build system changes against downstream Mirage/Solo5 using a **single command** (i.e. score the "Can you make an (end to end) build in one step?" on the [Joel Test](https://www.joelonsoftware.com/2000/08/09/the-joel-test-12-steps-to-better-code/)).

The E2E code temporarily lives at https://github.com/mato/e2e-mirage-solo5, and will likely move into the Solo5 repository under `tests/` for practical reasons once I'm happy with it.

**Comment by mato** [comment]
Progress update: The E2E tests have been merged in #340. Next up will be a PR with the build system refactor and removal of compile-time hvt specialization (step 1 here).

**Comment by mato** [comment]
PR for step 1 is now in #345.

**Comment by ehmry** [comment]
@mato looks good to me, tests still pass.

**Comment by mato** [comment]
Edited to reflect that this issue does not consider the actual changes for multiple device support, but only preparatory work (build system refactoring, sharing common code between tenders). All done here, so closing.
