### ISSUE TITLE
Running unprivileged kernels

### ISSUE THREAD

**Issue by fwsGonzo** [Solo5/solo5#328]
Can we run an unprivileged kernel on solo5 now? If not, when?

**Comment by mato** [comment]
I don't know what an "unprivileged kernel" is. Can you elaborate?

**Comment by fwsGonzo** [comment]
Just a kernel running unprivileged, and in this case being dependent on the solo5 API. It would be a more secure way to run a unikernel. On another topic, I don't see a way to generate randomness, and that would be a serious security problem in an unprivileged context. On normal hardware you have access to all kinds of random sources, such as WiFi frequencies and RDRAND when that is present, and while none are guaranteed, you can still build up enough randomness. With the solo5 API you don't have much to go on. Maybe I missed it, and you do have some entropy source.

**Comment by mato** [comment]
> Just a kernel running unprivileged

I still don't understand what you mean by "unprivileged". `hvt` / `virtio` / `muen` isolate the unikernel from its host using hardware virtualization. `spt` accomplishes the same using a minimal, strict seccomp filter. `genode` ... it depends, ask the Genode folks.

Watch our [talk](https://fosdem.org/2019/schedule/event/solo5_unikernels/) from this year's FOSDEM for more detail on Solo5 concepts, and also what it does _not_ do.

> I don't see a way to generate randomness

Correct, there is currently no API for obtaining entropy from the host. You can of course use CPU-based sources such as RDRAND and CPU jitter inside the unikernel, which is what MirageOS does. This may change at some point, but not now.

Meta: This is an issue tracker. The preferred place for general questions is the mailing list (https://github.com/solo5/solo5#contributing-and-community), which has the advantage that more people will see your question and can contribute to the discussion if they wish.

**Comment by mato** [comment]
I think this has been answered from my side, so closing.
