### ISSUE TITLE
Breaks with qemu master (post v3.1.0)

### ISSUE THREAD

**Issue by g2p** [Solo5/solo5#332]
This commit https://github.com/qemu/qemu/commit/ab969087da65e2f67a546cfc664901eda7029e36 might have broken the elf loading logic.

Running one of the Solo5 tests triggers
```
qemu-system-x86_64: Error loading uncompressed kernel without PVH ELF Note
```

**Comment by mato** [comment]
That seems to be an ABI change on the QEMU side. I'd suggest asking in the relevant places (mailing list?) what their plans with that are. If they're changing the "direct kernel boot" ABI I'm somewhat surprised that they are doing so without backward compatibility, but then it might just be a work in progress.

**Comment by mato** [comment]
Re-tested against QEMU 5.0, and this is no longer an issue, must have been a bug on QEMU master at the time.
