### ISSUE TITLE
Build error while installing mirage-entropy.0.4.1

### ISSUE THREAD

**Issue by evanpjensen** [Solo5/solo5#337]
```
opam reinstall mirage-entropy
mirage-entropy is not installed. Install it? [Y/n] y

The following actions will be performed:
  ∗ install mirage-entropy 0.4.1

<><> Gathering sources ><><><><><><><><><><><><><><><><><><><><><><><><><><><><>
[mirage-entropy.0.4.1] found in cache

<><> Processing actions <><><><><><><><><><><><><><><><><><><><><><><><><><><><>
[ERROR] The compilation of mirage-entropy failed at "/home/wont/.opam/opam-init/hooks/sandbox.sh build ocaml pkg/pkg.ml build
        --pinned false --tests false --with-mirage-xen false --with-mirage-solo5 true --with-ocaml-freestanding true".

#=== ERROR while compiling mirage-entropy.0.4.1 ===============================#
# context     2.0.3 | linux/x86_64 | ocaml-base-compiler.4.07.1 | https://opam.ocaml.org#0fed065c
# path        ~/.opam/default/.opam-switch/build/mirage-entropy.0.4.1
# command     ~/.opam/opam-init/hooks/sandbox.sh build ocaml pkg/pkg.ml build --pinned false --tests false --with-mirage-xen false --with-mirage-solo5 true --with-ocaml-freestanding true
# exit-code   1
# env-file    ~/.opam/log/mirage-entropy-98409-05296d.env
# output-file ~/.opam/log/mirage-entropy-98409-05296d.out
### output ###
# [...]
# /home/wont/.opam/default/include/solo5-bindings-virtio/crt/avx512dqintrin.h:1209:9: error: can’t convert a value of type ‘int’ to vector type ‘__vector(4) float’ which has different size
#  1209 |         __R);
#       |         ^~~
# Command exited with code 2.
# pkg.ml: [ERROR] cmd ['ocamlbuild' '-use-ocamlfind' '-classic-display' '-j' '4' '-tag' 'debug'
#      '-build-dir' '_build' '-plugin-tag' 'package(ocb-stubblr)' 'opam'
#      'pkg/META' 'CHANGES.md' 'LICENSE.md' 'README.md' 'lib/mirage-entropy.a'
#      'lib/mirage-entropy.cmxs' 'lib/mirage-entropy.cmxa'
#      'lib/mirage-entropy.cma' 'lib/entropy.cmx' 'lib/entropy.cmi'
#      'lib/entropy.mli' 'lib/dllmirage-entropy_stubs.so'
#      'lib/libmirage-entropy_stubs.a'
#      'X/mirage-freestanding/lib/libmirage-entropy_stubs+mirage-freestanding.a']: exited with 10



<><> Error report <><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><>
┌─ The following actions failed
│ λ build mirage-entropy 0.4.1
└─ 
╶─ No changes have been performed
```

[mirage-entropy-98409-05296d.out.txt](https://github.com/Solo5/solo5/files/2990699/mirage-entropy-98409-05296d.out.txt)
[mirage-entropy-98409-05296d.env.txt](https://github.com/Solo5/solo5/files/2990700/mirage-entropy-98409-05296d.env.txt)

Hi, I'm trying to troubleshoot this issue. I've attached the output files. It looks like a type error. But I don't see any other issues posted so I suspect it might be some kind of config error in disguise.

**Comment by mato** [comment]
That's an odd one. Since the error is in the compiler intrinsics, which we appropriate from the host toolchain and since you explicitly mentioned you're doing `opam reinstall`, here's a wild guess:

Is this an OPAM switch that you installed some time ago? Is it possible that you upgraded the compiler on your build system since the last time you used the OPAM switch?

Please provide some information about the build system: `cc -v`, `uname -a`, Linux distribution details, etc.

**Comment by evanpjensen** [comment]
The opam switch is recent `ocaml-base-compiler.4.07.1` but I have installed a new compiler I think more recently than the switch. 

```
wont@ubuntu:~/$ cc -v
Using built-in specs.
COLLECT_GCC=cc
COLLECT_LTO_WRAPPER=/usr/local/libexec/gcc/x86_64-pc-linux-gnu/9.0.1/lto-wrapper
Target: x86_64-pc-linux-gnu
Configured with: ../gcc/configure --enable-languages=c,c++ --enable-checking=release
Thread model: posix
gcc version 9.0.1 20190307 (experimental) (GCC) 

wont@ubuntu:~/$ uname -a
Linux ubuntu 4.15.0-46-generic #49-Ubuntu SMP Wed Feb 6 09:33:07 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

wont@ubuntu:~/$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.2 LTS
Release:	18.04
Codename:	bionic

```

The reinstall is an artifact I think from some forum posts I was following trying to resolve this. Is the way forward to do a new `opam init`?

**Comment by mato** [comment]
> The opam switch is recent ocaml-base-compiler.4.07.1 but I have installed a new compiler I think more recently than the switch.

That's the most likely cause of the problem. Also:

> gcc version 9.0.1 20190307 (experimental) (GCC) 

This appears to be an unreleased version of GCC, so all bets are off with that, sorry. I'd recommend sticking to released versions, we can't really support anything else.

> Is the way forward to do a new opam init?

No need for that, just create a new switch from scratch `opam switch create ...` and install the packages you want in it. You can also remove the old switch if you like.

**Comment by evanpjensen** [comment]
>just create a new switch from scratch

Now installs without issue. Thanks for your help!
