### ISSUE TITLE
Standalone test programs for Solo5 APIs

### ISSUE THREAD

**Issue by mato** [Solo5/solo5#37]
Currently the standalone test programs are limited to "Hello World" and "ping" (virtio only). We should have standalone tests for all of the Solo5 APIs, for both ukvm and virtio. This will require integrating nolibc from ocaml-freestanding to build the tests as post-namespacing Solo5 does not export any libc-like functionality.

**Comment by DrDub** [comment]
How would you envision the integration of nolibc? 
Copying it directly on the tests/ folder (as with the functions on test_ping_serve.c) or something more involved using git submodules?

**Comment by mato** [comment]
I'm leaning towards just taking a direct copy of the nolibc code from mirage/ocaml-freestanding, rather than using submodules or splitting out nolibc as a separate repository. The main reason for this is that I'd prefer the version used by ocaml-freestanding to include only the code required to support the OCaml runtime and nothing else. Conversely, the Solo5 test version might not need Openlibm at all (though that would require dropping eg. floating point support in `printf()`).

As you can see, I've not actually gotten around to doing any of this, so patches welcome :-)

**Comment by mato** [comment]
This is more or less done, in the sense that we've both removed some APIs (malloc), and added more standalone tests for the rest. Closing.
