### ISSUE TITLE
Installing solo5 on macos

### ISSUE THREAD

**Issue by bentxt** [Solo5/solo5#427]
Hi,
From the description on the mirageos website, I got the impression that solo5 can be installed on macos. Now when I try to run ./configure I get 

./configure.sh
configure.sh: ERROR: Unsupported toolchain target: x86_64-apple-darwin19.0.0

**Comment by mato** [comment]
Solo5 does not support macOS. (Though if someone is interested, `hvt` could probably be made to work, there is some ancient Hypervisor.framework code in #173.) I've clarified the MirageOS documentation in mirage/mirage-www#658.
