### ISSUE TITLE
Deploying to Google Cloud Compute fails with VM rebooting

### ISSUE THREAD

**Issue by mircea-cosbuc** [Solo5/solo5#429]
I was following [this guide](https://somerandomidiot.com/blog/2018/07/16/ditch-aws-build-host/) for deploying a static website as a MirageOS unikernel on Google Cloud and it seems like the VM is stuck rebooting after loading the unikernel, e.g.
```
SYSLINUX 6.04 6.04-pre2-11-gbf6db5b4* Copyright (C) 1994-2015 H. Peter Anvin et al
Loading unikernel.bin... ok
SeaBIOS (version 1.8.2-20191010_205345-google)
Total RAM Size = 0x0000000026600000 = 614 MiB
CPUs found: 1     Max CPUs supported: 1
Comparing RSDP and RSDP
Comparing RSDT and RSDT
Comparing FACP and FACP
Comparing FACS and FACS
return 0 for FACS vs FACS: SUCCESS
Comparing DSDT and DSDT
return 0 for DSDT vs DSDT: SUCCESS
return 0 for FACP vs FACP: SUCCESS
Comparing SRAT and SRAT
return 0 for SRAT vs SRAT: SUCCESS
Comparing APIC and APIC
return 0 for APIC vs APIC: SUCCESS
Comparing SSDT and SSDT
return 0 for SSDT vs SSDT: SUCCESS
Comparing WAET and WAET
return 0 for WAET vs WAET: SUCCESS
return 0 for RSDT vs RSDT: SUCCESS
return 0 for RSDP vs RSDP: SUCCESS
found virtio-scsi at 0:3
virtio-scsi vendor='Google' product='PersistentDisk' rev='1' type=0 removable=0
virtio-scsi blksize=512 sectors=2097152 = 1024 MiB
drive 0x000f2860: PCHS=0/0/0 translation=lba LCHS=1024/32/63 s=2097152
Sending Seabios boot VM event.
Booting from Hard Disk 0...

...
```

I was prompted to open an issue here after discussing it on `IRC#mirage`.

**Comment by mato** [comment]
Fixed in #431.

**Comment by ricarkol** [comment]
@mircea-cosbuc Just in case, if you are using the container option of mkimage (`solo5-virtio-mkimage.sh -d`), then you need to update the image first: `docker pull mato/solo5-virtio-mkimage`.

**Comment by yomimono** [comment]
Any chance of a release with the fix? I just got bit by this and wasted some time tracking it down before discovering that the fix is already present.

**Comment by mato** [comment]
@yomimono:

There will be a release soon-ish, I'm just waiting on having some Muen
updates so as not to have too much release churn.
