### ISSUE TITLE
Genode bindings failures on Debian Testing/Unstable

### ISSUE THREAD

**Issue by mato** [Solo5/solo5#441]
For some reasons `solo5-bindings-genode` fails on Debian Testing and Unstable:
```
# ld -nostdlib -z max-page-size=0x1000 -shared -gc-sections --eh-frame-hdr -Ttext=0x01000000 --dynamic-linker=ld.lib.so -rpath-link=. -T /home/opam/.opam/4.10/.opam-switch/build/solo5-bindings-genode.0.6.4/bindings/genode/genode_dyn.ld /home/opam/.opam/4.10/.opam-switch/build/solo5-bindings-genode.0.6.4/bindings/genode/solo5.lib.so \
#     test_tls.genode.o manifest.genode.o -o test_tls.genode
# ld: test_tls.genode: error: PHDR segment not covered by LOAD segment
# make[2]: *** [../Makefile.tests:73: test_tls.genode] Error 1
# make[2]: Leaving directory '/home/opam/.opam/4.10/.opam-switch/build/solo5-bindings-genode.0.6.4/tests/test_tls'
# make[1]: *** [GNUmakefile:33: test_tls] Error 2
# make[1]: Leaving directory '/home/opam/.opam/4.10/.opam-switch/build/solo5-bindings-genode.0.6.4/tests'
# make: *** [GNUmakefile:70: tests] Error 2
```
But I've seen this error before and it is unrelated to the package. Merging. Thanks a lot!

_Originally posted by @kit-ty-kate in https://github.com/ocaml/opam-repository/pull/15935#issuecomment-593514952_

This is presumably due to toolchain changes in Debian Testing/Unstable.

**Comment by mato** [comment]
Ping @ehmry? See also another report in #444.

**Comment by ehmry** [comment]
Yes, I would recommend to disable Genode builds unless there are explicitly requested, and then using a Genode specific toolchain. I will look into it tomorrow.
