### ISSUE TITLE
Support building with nix

### ISSUE THREAD

**Issue by Mic92** [Solo5/solo5#497]
I just want to drop this expression here, that allows to build solo5 with nix:

```
with import <nixpkgs> {};
stdenv.mkDerivation {
  name = "env";
  nativeBuildInputs = [
    bashInteractive
    pkg-config
  ];
  hardeningEnable = [ "pie" ];
  buildInputs = [
    libseccomp
  ];
}
```

Also needs https://github.com/Solo5/solo5/pull/496

**Comment by ehmry** [comment]
Solo5 is in Nixpkgs so this can be closed.

However, Solo5 from Nixpkgs cannot be used to build unikernels after pkg-config was replaced with NIH compiler scripts.
