### ISSUE TITLE
Do an audit about `sleep()`

### ISSUE THREAD

**Issue by dinosaure** [Solo5/solo5#533]
#525 highlights a possible issue about the way that the time is handled. A fix on tests seems needed but it probrably hidden something bigger than what we expect. I created this issue to keep track that and be sure that we don't miss anything.

**Comment by reynir** [comment]
I see that on SPT we use `clock_gettime()` with `CLOCK_MONOTONIC`. The man page on Linux says:

> [**CLOCK_MONOTONIC**
> Clock that cannot be set and represents monotonic time since some unspecified starting point. This clock is not affected by discontinuous jumps in the system time (e.g., if the system administrator manually changes the clock), but is affected by the incremental adjustments performed by adjtime(3) and NTP.](https://linux.die.net/man/2/clock_gettime)

So perhaps it's due to the incremental time adjustments?

On hvt x86_64 `rdtsc` is used to read the [time stamp counter](https://en.wikipedia.org/wiki/Time_Stamp_Counter). I'm not sure how that works with virtualization (kvm etc.).

**Comment by dinosaure** [comment]
`CLOCK_MONOTONIC`, `rdtsc` and clock available on microkernels are aligned by the same semantic: a monotonic clock. The drift of such clock is expected even in tests (where we should rather try to control the execution of the microkernel so that the host system does not shift this clock by suspending).

I will probably add comments to explain what is expected in these tests and what to do if a user sees an error in them.

I've already increased the margin of error for this test earlier. So I think it should be fine. For more details about the clock, the reader can redirect to: #549.
