### ISSUE TITLE
Add into our CI OpenBSD 6.9

### ISSUE THREAD

**Issue by dinosaure** [Solo5/solo5#534]
#450 introduces a nice improvement about the OpenBSD support. However, our CI does not yet test it. We probably should extend our CI with OpenBSD 6.9.

**Comment by hannesm** [comment]
Likely we'd want OpenBSD at its latest release, which at the moment is 7.2.

**Comment by adamsteen** [comment]
Let me know if you need anything?

**Comment by dinosaure** [comment]
Currently, I tried to deploy an OpenBSD 6.8 but, since #526, we need `realpath` which seems available only for >= OpenBSD 7.1. Our infra requires a `qcow2` image of an OpenBSD system. It will be really nice to have one for OpenBSD 7.1. By this way, I will be able to fix the CI.

**Comment by dinosaure** [comment]
So a CI for OpenBSD 7.2 is active, see this comment about some details: https://github.com/Solo5/solo5/pull/535#issuecomment-1304794602. The issue can be closed now.
