### ISSUE TITLE
Multiple virtio net devices

### ISSUE THREAD

**Issue by palainp** [Solo5/solo5#580]
Dev devs,

For experimentation purposes using mirageOS unikernels with GNS3, I need to use multiple network devices (at least 2, e.g. for a firewall unikernel). So far, using virtio target has worked well, but according to the code, the implementation is currently limited to a single net device: https://github.com/Solo5/solo5/blob/5478c255911e1dae6c9ab1f448daddf0fb46ea37/bindings/virtio/virtio_net.c#L283-L284

Maybe I'm getting it wrong with virtio and can use a different target, or maybe I can work on support for multiple net interfaces (in which case, what would be the best way to code this functionality?).

Any insight would be helpful :)
Best.

**Comment by hannesm** [comment]
Dear @palainp, there has been work earlier on virtio and multiple network devices https://github.com/Solo5/solo5/pull/377

As far as I remember, the main issue was: who needs that? and the other about naming -- in hvt & spt we have this very nice naming (`solo5-hvt --net:service=tapN`) -- and we haven't found a nice way to transport names in virtio -- so how would such a mapping happen (one choice would be "first NIC passed is the first named interface"). If there's some idea how to do that, I guess we can just merge such a PR (see at the earlier PR for discussions).

**Comment by palainp** [comment]
Dear @hannesm, thank you for your reply, I missed that PR. To answer the first question about "who needs that?" I'm now one of them :)
For the second question I'll check the PR and play with it a bit (probably it'll need some sort of rebase). Thanks for the pointer!

**Comment by hannesm** [comment]
I agree that it is useful to have. I find the manifest in solo5 very nice, but do not know enough of virtio to understand whether / how such a mapping could take place. AFAICT from operational experience, it is just NIC_0..NIC_n, no names, and as an operator you've to remember which network interface is connected where.

**Comment by palainp** [comment]
Solved by #581
