### ISSUE TITLE
Validate image passed to ukvm is in ELF format

### ISSUE THREAD

**Issue by myechuri** [Solo5/solo5#88]
When a qcow2 image is passed to ukvm, it went past [load_code](https://github.com/Solo5/solo5/blob/master/ukvm/ukvm-core.c#L835), and crashed later in [vcpu_loop](https://github.com/Solo5/solo5/blob/master/ukvm/ukvm-core.c#L708) with KVM_EXIT_SHUTDOWN.

Thanks to debugging help from @ricarkol and @rean, root cause was determined to be unsupported image format. The image i passed to ukvm was qcow2 (which happens to be the default image format for OSv), which ukvm proceeded to load as ELF without issues.

It would be good to validate image format in [load_code](https://github.com/Solo5/solo5/blob/master/ukvm/ukvm-core.c#L835) itself in order to preempt vcpu_loop execution for code bound to crash. Also, it would be good to inform end user reason for failure. Will send PR for the validation change.

**Comment by mato** [comment]
Fixed by #89.
