### ISSUE TITLE
Host CPU feature discovery

### ISSUE THREAD

**Issue by mato** [Solo5/solo5#9]
Moving feature discovery discussion from #6, @djwillia writes:

> It seems like we may need to do a bit of hardware discovery. I think it should be done in ukvm rather than in the guest. CPU speed is a place that some "discovery" is happening, but it is a horrible hack:
> https://github.com/djwillia/solo5/blob/ukvm-mirage/ukvm/ukvm.c#L687
> It might make sense to have a little configuration script which figures out what we need to know and generates a header or something for ukvm.c What do you think?

**Comment by mato** [comment]
@djwillia Yes, I saw that hack :-). 

Agreed on the need to do some feature discovery. Some suggestions:
* First, collect what features we do or do not want/need to depend on as we hit them (it gets fairly complex rapidly, especially with timekeeping).
* Second, decide on a minimal required host CPU feature set, weighing "implementation and architecture simplicity gained by use of feature X" vs. "userbase lost by not supporting processors without X".

My personal preference would be to lean towards the former (simplicity), there is always QEMU if you want the runs-everywhere kitchen sink. What do you think?

**Comment by mato** [comment]
I just realised I didn't really answer your original question about _where_ to do CPU feature detection. This should be done at runtime in ukvm, not at compile time, as the CPU you're deploying on may not be identical to the CPU you are building on. For clock speed, this is fairly easy (BTDT) to estimate using `RDTSC`, as long as some host CPU features are available (Invariant TSC, Constant/"Non stop" TSC). `CPUID` can be used to determine if these are available. Of course, if you're running in a VM then the hypervisor can lie about CPUID, but that's not our concern.

**Comment by mato** [comment]
(Removed part of my previous comment about TSC estimation since that's bogus, will follow up later.)

**Comment by djwillia** [comment]
Ah, of course, runtime makes sense, especially for breaking issues.  I have some half-baked notion in my head related to immutable infrastructure and doing a "last-mile" compilation at deploy time, which seems to have confused me.  

In general, though, it does seem there is a difference between 
- one binary that runs everywhere the userbase wants, and 
- the ability to build a binary that runs where the userbase wants.  

At some point, I want to explore the modularization of ukvm, at which time the latter becomes interesting.  In some sense the latter means more configuration options and potentially more deployment complexity, but also a simpler implementation.  The tradeoff isn't clear to me.

For now it seems like we should do runtime CPU speed discovery in ukvm, but I don't know if it's worth worrying about 1GB vs 2MB page discovery yet.  I would guess 2MB pages are always available if VT is.  There ought to be an easy way to do it (e.g., some syscall or something) considering we're running as a Linux userspace process!

**Comment by mato** [comment]
Regarding guest page size, I don't think we have anything to gain from 1GB pages. 2MB pages will be supported everywhere long mode is, i.e. on any x86-64 processor. In future we may want to move to 4KB pages or a mix of the two in order to take advantage of features like NX without wasting too much virtual address space.

**Comment by mato** [comment]
AFAICT there's nothing to do here. Various parts of this topic have since been improved, fixed or are no longer required, so I'm closing this issue.
